USE CSI_ClientCOS_642
SELECT
	TABLE_SCHEMA
	,TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE
	TABLE_NAME LIKE '%origin%'------------Insert query here
	AND TABLE_NAME NOT LIKE 'ef%'
	AND TABLE_SCHEMA NOT LIKE 'history'
	AND TABLE_TYPE LIKE 'BASE TABLE'
ORDER BY
	TABLE_NAME
	,TABLE_SCHEMA

-------------------------------------------------------------------------------Columns

SELECT
	TABLE_SCHEMA
	,TABLE_NAME
	,COLUMN_NAME
	,ORDINAL_POSITION
	,IS_NULLABLE
	,DATA_TYPE
	,CASE 
		WHEN
			DATA_TYPE LIKE '%char'
			OR DATA_TYPE LIKE '%binary'
			THEN CAST(CONCAT('Char/Octet Length: ',CHARACTER_MAXIMUM_LENGTH,', ',CHARACTER_OCTET_LENGTH) AS VARCHAR(36))
		WHEN
			DATA_TYPE LIKE 'DECIMAL'
			OR DATA_TYPE LIKE 'INT'
			THEN CAST(CONCAT('Precision,Radix,Scale: ',NUMERIC_PRECISION, ', ',NUMERIC_PRECISION_RADIX,', ',NUMERIC_SCALE) AS VARCHAR(36))
		WHEN
			DATA_TYPE LIKE 'DATE%'
			THEN CAST(CONCAT('Precision: ',DATETIME_PRECISION) AS VARCHAR(36))
	END AS EXTRA_DATA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE
	COLUMN_NAME LIKE '%%'
	AND TABLE_NAME NOT LIKE 'EF%'
	AND TABLE_SCHEMA NOT LIKE 'history'
ORDER BY
	--ORDINAL_POSITION
	COLUMN_NAME
	,TABLE_NAME
	,TABLE_SCHEMA