USE CSI_ClientCOS_642

SELECT
	TABLE_SCHEMA
	,TABLE_NAME
	,COLUMN_NAME
	,ORDINAL_POSITION
	,IS_NULLABLE
	,DATA_TYPE
	,CASE 
		WHEN
			DATA_TYPE LIKE '%char'
			OR DATA_TYPE LIKE '%binary'
			THEN CAST(CONCAT('Char/Octet Length: ',CHARACTER_MAXIMUM_LENGTH,', ',CHARACTER_OCTET_LENGTH) AS VARCHAR(36))
		WHEN
			DATA_TYPE LIKE 'DECIMAL'
			OR DATA_TYPE LIKE 'INT'
			THEN CAST(CONCAT('Precision,Radix,Scale: ',NUMERIC_PRECISION, ', ',NUMERIC_PRECISION_RADIX,', ',NUMERIC_SCALE) AS VARCHAR(36))
		WHEN
			DATA_TYPE LIKE 'DATE%'
			THEN CAST(CONCAT('Precision: ',DATETIME_PRECISION) AS VARCHAR(36))
	END AS EXTRA_DATA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE
	TABLE_NAME LIKE 'feerate'
	AND COLUMN_NAME LIKE '%amount_cap%'
	AND TABLE_NAME NOT LIKE 'EF%'
	AND TABLE_SCHEMA NOT LIKE 'history'
ORDER BY
	--ORDINAL_POSITION
	COLUMN_NAME
	,TABLE_NAME
	,TABLE_SCHEMA

SELECT
	*
FROM SYS.key_constraints


SELECT
	KC.name
	,C.TABLE_NAME AS PARENT_TABLE
	,C.COLUMN_NAME AS PARENT_COLUMN
	,CC.TABLE_NAME AS REFERENCED_TABLE
	,CC.COLUMN_NAME AS REFERENCED_COLUMN
FROM SYS.foreign_key_columns AS FKC
	JOIN sys.key_constraints AS KC
		ON KC.object_id = FKC.constraint_object_id
	JOIN INFORMATION_SCHEMA.COLUMNS AS C
		ON C.ORDINAL_POSITION = FKC.referenced_column_id
	JOIN INFORMATION_SCHEMA.COLUMNS AS CC
		ON CC.ORDINAL_POSITION = FKC.constraint_column_id


SELECT 
	COUNT(*)
FROM SYS.foreign_key_columns

SELECT
	COUNT(*)
FROM INFORMATION_SCHEMA.COLUMNS

SELECT
	C.TABLE_NAME AS PARENT_TABLE
	,C.COLUMN_NAME AS PARENT_COLUMN
	,CC.TABLE_NAME AS REFERENCED_TABLE
	,CC.COLUMN_NAME AS REFERENCED_COLUMN
FROM SYS.foreign_key_columns AS FKC
	JOIN INFORMATION_SCHEMA.COLUMNS AS C
		ON C.ORDINAL_POSITION = FKC.referenced_column_id
	JOIN INFORMATION_SCHEMA.COLUMNS AS CC
		ON CC.ORDINAL_POSITION = FKC.constraint_column_id
WHERE
	C.TABLE_NAME NOT LIKE 'ef_%'
	AND CC.TABLE_NAME NOT LIKE 'ef_%'
	AND C.TABLE_NAME NOT LIKE '%history%'
	AND CC.TABLE_NAME NOT LIKE '%history%'