USE CSI_Admin
GO

DECLARE
	@JobID AS TABLE
	(
		ID UNIQUEIDENTIFIER
	)
DECLARE
	@CurDate AS DATE

SET
	@CurDate = CAST(GETDATE() AS DATE)

INSERT INTO @JobID
	SELECT DISTINCT
		PROCESSOR_JOB_ID
	FROM ProcessorJob
	WHERE
		CAST(PICKUP_ON AS DATE) = @CurDate

SELECT
	A.*
FROM @JobID AS JIDO
	CROSS APPLY
	(
		SELECT TOP(1)
			PJ.PROCESSOR_JOB_ID AS PROCESSOR_ID
			,CAST(PICKUP_ON AS DATE) AS PICKUP_DATE
			,CAST(PICKUP_ON AS TIME) AS PICKUP_TIME
			,PJS.PROCESSOR_JOB_STATUS_NAME
		FROM ProcessorJob AS PJ
			JOIN ProcessorJobStatus AS PJS
				ON PJS.PROCESSOR_JOB_STATUS_ID = PJ.PROCESSOR_JOB_STATUS_ID
		WHERE
			JIDO.ID=PJ.PROCESSOR_JOB_ID
	) AS A
ORDER BY
	ID DESC

SELECT
	A.*
FROM @JobID
	CROSS APPLY
	(
		SELECT
			ROW_NUMBER() OVER
			(
				PARTITION BY PROCESSOR_JOB_ID
				ORDER BY
					PROCESSOR_JOB_ID
					,CREATED_ON
			) AS ROWNUM
			,PROCESSOR_JOB_ID
			,APPLICATION_LOG_MESSAGE
			,CAST(CREATED_ON AS DATE) AS CREATED_DATE
			,CAST(CREATED_ON AS TIME) AS CREATED_TIME
		FROM ApplicationLog
		WHERE
			PROCESSOR_JOB_ID = ID
	) AS A

/* Put error here
*/
	